// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WelfareLinkPRJ.Data;

#nullable disable

namespace WelfareLinkPRJ.Migrations
{
    [DbContext(typeof(WelfareDbContext))]
    [Migration("20260325091423_disbursement_table_update")]
    partial class disbursement_table_update
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WelfareLinkPRJ.Models.Benefit", b =>
                {
                    b.Property<int>("BenefitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BenefitID"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<int>("ApplicationID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BenefitID");

                    b.ToTable("Benefits");
                });

            modelBuilder.Entity("WelfareLinkPRJ.Models.Disbursement", b =>
                {
                    b.Property<int>("DisbursementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DisbursementID"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<int>("BenefitID")
                        .HasColumnType("int");

                    b.Property<int>("CitizenID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("OfficerID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DisbursementID");

                    b.HasIndex("BenefitID");

                    b.ToTable("Disbursements");
                });

            modelBuilder.Entity("WelfareLinkPRJ.Models.Disbursement", b =>
                {
                    b.HasOne("WelfareLinkPRJ.Models.Benefit", "Benefit")
                        .WithMany("Disbursements")
                        .HasForeignKey("BenefitID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Benefit");
                });

            modelBuilder.Entity("WelfareLinkPRJ.Models.Benefit", b =>
                {
                    b.Navigation("Disbursements");
                });
#pragma warning restore 612, 618
        }
    }
}
